### ISSUE TITLE
problem with two step wallet connection

### ISSUE THREAD

**Issue by mufarex** [bitlogik/pyWalletConnect#6] opened 2022-02-20 11:16 UTC
Hello bitlogik. Thank you for your greate pyWallett. I am trying to connect a wallet to dextools site with your example code. dextools has two-step for wallet connection. when I first use  wallet_dapp.reply_session_request(req_id, account.chainID, account.address) the wallet connects correctly but I don't know how to pass step two which is wallet verification. Please help me with this issue. Thanks

**Comment by bitlogik** [comment] 2022-02-20 15:00
The pyWalletConnect library allows your wallet software to connect to a WalletConnect dapp service, it provides queries from the dapp, and then you can send back the response to the dapp. The response is computed by your wallet software. The provided CLI demo only connects to a dapp, and then displays all the methods call queries it gets from the dapp, without any processing of these queries.

The DexTools dapp, like many dapps, allows you to use WC to connect your wallet. Immediately after the wallet connection established, it sends a _personal_sign_ query, to be signed (with a prefix) by the wallet account. This is what they are calling "second step". This ensures the user has the private keys for this account. This step is not a WalletConnect side, but rather a wallet side message. The DexTools dapp sends signature command to the wallet, using the WalletConnect connection tunnel. In a way, it is similar as a transaction request. This message query and its reply are carried by the WalletConnect "tunnel" system, and this library only acts as a tool to connect the tunnel, makes it happen. But then this library is not a wallet, it doesn't offer any capability to sign any message. This is just a communication tunnel between a dapp and a wallet, as the WalletConnect standard is by design.

With DexTools "second step", using the _.get_message()_ method returns something like this :
` (1645362489625000, 'personal_sign', ['0x3aa33c6cb4bd6986edebe59446b7cfb7e50b0a32d114a6390dc6c35b3b09c68398f45cbc193ab159b05f5e6576ba317c90d97325ea955d525897a120d7dfde7eed4db97cce21362746fd2296a4ab89133', '0xYourAddr3ss'])`

_get_messages()_ provides (id, method, params)  or (None, "", []) when nothing is available.

You wallet software, connected to the dapp thanks to this library needs to process this query. In this case your Python app should sign according to the "_personal_sign_ standard", and you can upload back the response using the _.reply(id, result)_ method, using the same id as the query.
It gives something like this when you call the reply method :
`.reply( 1645362489625000, "0x5728057505e527c4c3450ec9e5dab75a167d230fe9d81339f9a30fdd652188d7747c9d424340f586a8eaddcb12c53694d333a76495b6da496bf01de500e053ba1b")`

Your application which uses pyWalletConnect needs to dispatch the dapp queries into the relevant handlers and to process them by the wallet part. pyWalletConnect is not a wallet, just a WalletConnect library.
Example of wallet dispatching implementation using pyWalletConnect :
The _get_messages()_ method in the uniblow wallet dispatches the WC queries :
https://github.com/bitlogik/uniblow/blob/master/wallets/ETHwallet.py#L450
For "personal_sign" method, the wallet calls its _process_sign_message_ method. PyWalletConnect is only a connection library to connect your Python wallet with a dapp (using the WalletConnect system).

In your case for dextools, a "personal_sign" request call is received just after the WC connection, and it must be handled by your wallet, as any other dapp queries.

We tested an integration of pyWalletConnect in our wallet Uniblow, and it works very well with the dextolls service. The wallet handles the query dispatching and displays a graphical modal to the user, to get the confirmation of the signature.
This signature response is sent back (if approved) using _reply(..)_, as a standard wallet response.

Note the **_.reply_session_request_ method shall only be used once** to finalize the WC connection. And then only the _.reply(id, result)_ method shall be used by the wallet part, together with _get_messages()_ to read the queries from the dapp.
Your message suggests that your connection is OK, so your app calls _.from_wc_uri_ (creator), and then _.reply_session_request_. Once _.reply_session_request_ is sent, the WC tunnel is opened and operational. And your software should only use  _get_messages()_ and _.reply(id, result)_ methods.

**Comment by mufarex** [comment] 2022-02-20 20:49
Thank you for your complete answer. I used your tips and I get some results. I want to share my code for getting the best guide from you. after opening the walletconnect barcode:

1) wallet_dapp = WCClient.from_wc_uri(str(Tk().clipboard_get()))
2) mesage=wallet_dapp.get_message()
and this is the result: {'peerId': '411be2a5-4f95-4a63-b983-64e7183147ed', 'peerMeta': {'description': 'Ultimate Hub and Defi App For Uniswap, Pancakeswap, Quickswap, Spookyswap, Cronaswap and DEX trading.', 'url': 'https://www.dextools.io', 'icons': [...], 'name': 'User Account - DEXTools'}, 'chainId': 1}
what is the next step to connect and verify the wallet. Thanks

**Comment by bitlogik** [comment] 2022-02-20 21:40
Please read carefully the Readme and the interface methods description. Some parts maybe unclear. I detail more here under.

The connection should be opened with the _from_wc_uri()_ contructor, then calling _.open_session()_ an finally with _reply_session_request_ once the user approved the session. You get the _reply_session_request_ request id argument directly from the _open_session_ return.

-> You need to call _open_session_ immediately after to get the session request info. Must be called right after a WCClient creation.
-> You need to call reply_session_request, after user connection approval (after _open_session_). That sends a session approval message with the wallet info, when the user approves the connection session request in the wallet.

Then, once the session is opened (after a positive _reply_session_request_), you can use _get_message_ and _reply_. But these 2 methods designed to read and write in the tunnel, are **not used before** the session is entirely connected.

To recap, this is something like that :
1. `wcc = WCClient.from_wc_uri( wc_uri_str ) `
2. `session_data = wcc.open_session()`
At this stage session_data[0] is the RPCqueryID needed for the session confirmation reply, session_data[1] is the chainID, proposed by the dapp (if present), session_data[2] is the dapp description data
According to WalletConnect, you can show the dapp data to the user and ask her to confirm the session to this dapp.
Once the user approved this dapp, the session can be confirmed and finalized. it used the wallet data, and the RPCid read from open_session. reply_session_request also sends the wallet data to the dapp (chain and address).
3. `wcc.reply_session_request( session_data[0] , ChainId, Account_Address )`
Now the WC session is fully opened and operational.
You can now use _get_message()_ and _reply(..)_ to communicate with the dapp. You can "pump" get_message, read it from time until exhausted. And when a message is available your software process it, and send back the result.
4. `RPCid, method, params = wcc.get_message()`
5. Process the request and build the response
6. `wcc.reply(RPCid, response_str)`
So you get queries from the dapp, such as transaction signing, your wallet part are handling the requests. 4/5/6 should be done in a loop, or I advise even to trigger the 4 reading part from a thread timer with a interval to read it from time to time. _reply_ uses the request id read from _get_message_ to send back the associated response.

You can think/view the methods as : 
Finalizing the connection (called once) : read = open_session(), write = reply_session_request(..)
Data exchange once tunnel is operational (called multiple times) : read = get_message(), write = reply(..)

Note also that _get_message_ is non-blocking. It won't wait for available data, and always returns immediately a response. (None, "", []) if nothing. If the first returned argument of get_message is None, there's is nothing to process, and you wait some time for the next read interval, and so on.

The DexTools "second step" is just a "personal_sign" request call send just after the WC connection. But this is a standard wallet request. You will get with _get_message_, as any other dapp request. So you process it and send the reponse back using _reply_.
This dextools step is not part of the WalletConnect standard. They are just making a wallet request once the session is fully opened. Some others dapps acts the same, like OpenSea, they trigger a sign request right after the WC tunnel opened.

**Comment by mufarex** [comment] 2022-02-20 21:58
would you please check this code. it always gets None response:

wallet_dapp = WCClient.from_wc_uri(str(Tk().clipboard_get()))
session_data = wallet_dapp.open_session()
wallet_dapp.reply_session_request(session_data[0], 1, 0x6C7D18540c59109D608a25f3b60a0052cBacF9bb)
read_data = wallet_dapp.get_message()
while read_data[0] is  None:
        try:
            time.sleep(0.3)
            # get_message return : (id, method, params) or (None, "", [])
            read_data = wallet_dapp.get_message()
            

        except:
            continue

**Comment by bitlogik** [comment] 2022-02-20 22:07
Looks good to me.
Remove the try/except, there's maybe an exception inside, and this goes after the while loop (continue). So it can continue if there's an exception but without reading any message.

I propose the following "quick&dirty" snippet.
```
wallet_dapp = WCClient.from_wc_uri( wc_uri )
session_data = wallet_dapp.open_session()
wallet_dapp.reply_session_request(session_data[0], 1, <Address>)
read_data = (None, None, None)
print("waiting for a dapp request ...")
while read_data[0] is None:
    time.sleep(0.5)
    # get_message return : (id, method, params) or (None, "", [])
    read_data = wallet_dapp.get_message()
print("The first dapp request :", read_data[1], read_data[2])
# To process and reply
```

Then you need to periodically call _get_message_ to monitor the request from the dapp.

**Comment by bitlogik** [comment] 2022-02-20 22:12
Also, this works in a reasonable time (almost immediately) with DexTools . But the vast majority of the dapps are not sending anything until the user makes a request in the web page (for example trigger a swap).
Plus, in a GUI, you can't really use time.sleep, but needs to use a timer interval (_after_ in Tk).

**Comment by mufarex** [comment] 2022-02-20 22:19
Actually, I used the above code and it goes to an infinite loop. In dextools  a verify wallet button appears after you connect the wallet I clicked that but nothing happened! :(

**Comment by bitlogik** [comment] 2022-02-20 23:04
OK, tomorrow I'll see that.
Very weird because the Uniblow wallet is actually uses this library, and it received the first dextools request (what they call the second step), and the full connection was achieved (WC connection and wallet signature). In my memory, the request from dextools even fires up right after the connection, no need to click on the verify button.

**Comment by bitlogik** [comment] 2022-02-21 10:06
OK. After some tests, we found the issue is because you provide the address as an integer (0x is interpreted as in integer written as hexadecimal), and not as a string.
reply_session_request packs this as it received : "accounts": [account_address],
And when receiving a bad address format, the dextools dapp doesn't send the "personal_sign" message, hence the infinite loop. The dapp doesn't send any message, nor closing the connection.

We'll update the documentation to update these points. Though, the provided examples are clear this is a string. Also if you look [at the WalletConnect standard](https://docs.walletconnect.com/tech-spec#session-update), the _accounts_ attribute is a string array. We are considering to add checks for the type of the arguments to ease the use of this library.

I confirm the dextools dapp is sending the "personal sign" request without any user interaction. It is sent immediately upon WC full connection established.

Notes for your tests :
- The connection is immediately closed when the WCClient object is deleted. So using a very simple script as this one : a loop waiting the first message, then it reaches the end and quits : this closes the connection, and the dapp gets back to an unconnected state.
- Make sure you refresh the wc link between your tests. Else the session request can't be received, this is single live message, sent once. In case you reuse an old wc link, you received `pywalletconnect.client.WCClientException: sessionRequest timeout`, because there would be no sessionRequest received in time. A session is unique and sometimes, the wc link given by a dapp is not refreshed properly during the test, and that causes this.
- This library uses the standard log output. You can enable the debug logging, and it will output (in the standard output) many internal details of what happens internally. Very useful for development.
Here's what you can add in your main/upper program to activate this :
```
from logging import basicConfig, DEBUG
basicConfig(level=DEBUG)
```

**Comment by mufarex** [comment] 2022-02-21 10:22
Hello Bitlogik. Thank you for your help. It worked. so after receiving the personal sign in the wcc.reply(RPCid, response_str) what should be the response_str.

**Comment by mufarex** [comment] 2022-02-21 10:29
Hello Bitlogik. Thank you for your help. It worked

**Comment by mufarex** [comment] 2022-02-21 13:48
In READ.ME you used this code :
def process_sendtransaction(call_id, tx):
    # Processing the RPC query eth_sendTransaction
    # Collect the user approval about the tx query
    < Accept (tx) ? >
    if approved :
        # Build and sign the provided transaction
        <...>
        # Broadcast the tx
        # Provide the transaction id as result
        return "0x..." # Tx id
and with process_sendtransaction function made the result for the .reply . Is it necessary for me to do like this?

**Comment by bitlogik** [comment] 2022-02-21 15:56
> I got the params and I send a response like this wallet_dapp.reply(RPCid,params[0]). when you connect the wallet manually immediately after verification, the page changes and shows plans for accounts and other things but when I do it with code nothing changes. 

Probably it is related to what I explained as a note for your tests just upper : "The connection is immediately closed when the WCClient object is deleted. So using a very simple script as this one : a loop waiting the first message, then it reaches the end and quits : this closes the connection, and the dapp gets back to an unconnected state."
When your Python script ended, it destroys all the internal Python objects, including the WCClient you opened. And the WCClient automatically sends a closing session message to the dapp (like a dying-gasp). So the dapp page reverts to the state where it is not connected, and you think nothing has changed.
The WCClient needs to be kept alive (keep a reference to it), not killed (not deleted). It offers a tunnel to your dapp. you have the methods _get_message_ to read and _reply_ to write to the dapp. When deleted it closes the tunnel, signaling to the dapp the end of the user session.

Second thing, I'm not sure why you reply with _params[0]_ as the reply data.

>  Is it necessary for me to do like this?

I don't know exactly your goal. In case you need to reply to an "eth_sendTransaction" request from the dapp, yes you need to do that.

This code part is an example of a request handler that your wallet offers. In the Readme, we provide a boilerplate example to illustrate how one can dispatch the requests types to their respective handlers in your wallet, and how to reply to the dapp.
This library offers a WalletConnect tunnel, to link a Python wallet with a web dapp (through WC). It doesn't offer any wallet capability such as transaction building, nor signing.
In the example, _process_sendtransaction_ is the handler function for the "eth_sendTransaction" request, dispatched by the _watch_messages_ function.
pyWalletConnect brings to your Python code an easy way to read the dapp requests (once connected, with `get_message()`). Your software wallet processes the result, and using the WCClient object it just replies the result with `.reply(call_id, result)`

Generally speaking, we don't support for free any code development outside of our open-source codes capabilities. We assist people for free to clarify the use our free softwares, and provide support for free for bug fixes and improvements. We are providing paid support to develop outside of the scope of our public code. You can[ contact us (link)](https://bitlogik.fr/contact.html) in case you want code development for specific tasks. If you need a Python wallet, you can look at [uniblow, the open-source blockchain wallet that we have developed](https://github.com/bitlogik/uniblow). This wallet uses this library, and actually this library was developed to provide WalletConnect capability to this software wallet. We just chose to make it a different and separate package.

Take care to protect your private keys diligently if they hold some decent values.

**Comment by bitlogik** [comment] 2022-02-21 15:58
Also for the wallet part, you may use Web3py which offers methods and interfaces similar to Web3.js. https://web3py.readthedocs.io/en/stable/

**Comment by mufarex** [comment] 2022-02-21 17:23
First I appreciate your kind attention. 
As you asked:#Second thing, I'm not sure why you reply with params[0] as the reply data.
As you said in your first comment after .get_message when I get the personal sign I should use .reply for sending the result.
this is my code:
RPCid, method, params = wallet_dapp.get_message() 
wallet_dapp.reply(RPCid,params[0])

after replying the page does not shows any sign of verification As I said above. Thank you

**Comment by bitlogik** [comment] 2022-02-21 18:20
You send the response computed for the _personal_sign_ request from the dapp using the _reply_ method. The first argument is the request ID, that you get when you read the related request from get_message. Second argument is the data for the reply, the response data.
You wallet software, connected to the dapp thanks to this library needs to process the query request. In this case, your Python application should sign according to the "personal_sign standard", and you can upload back the response using the .reply(id, result) method, using the same id as the query.

Dextools "second step" is a wallet call (specifically a personal_sign request), once the WalletConnect session is fully connected. This is a standard wallet call, and these messages are not handled by pyWalletConnect. This library only gives you the dapp request (wallet calls), and the ability to send the response for these requests (once processed by your wallet software part).

From what you are telling, it looks like you are just responding to the request with the message to "personal_sign" (first param in the request is the message data), and not the signature which is expected as the reply for this request. So I imagine the page rejects the verification, as the signature is not correct. You need to understand that pyWalletConnect gives you the dapp requests, and it allows you to send the reply for these requests. But the processing to compute the reply is not part of this library. pyWalletConnect only takes care about the communication and the tunnel with the dapp. It provides request queries to the Python wallet side and you can write back responses to the dapp. It doesn't offer any capability of a wallet. It doesn't compute the response for the dapp queries, which are wallet commands. This is summarized in the first 2 sentences in the Readme describing the app purpose : _A Python3 library to link a wallet with a WalletConnect web3 app. This library connects a Python wallet with a web3 app online, using the WalletConnect standard_. You need to do this wallet part yourself, eventually using [the web3.py library](https://pypi.org/project/web3/) or some [Uniblow code parts](https://github.com/bitlogik/uniblow/blob/master/wallets/ETHwallet.py). Our company would be very happy to assist you in the design and development of your project, if you need skills developers onboard.

**Comment by mufarex** [comment] 2022-02-22 08:35
Hi Bitlogik. yes, I need some help to compute the personal sign response. how much should I pay your developer to do that for me? and I'm a student and I hope you notice this in the payment :)

**Comment by mufarex** [comment] 2022-02-22 08:36
Hi Bitlogik. yes, I need some help to compute the personal sign response. how much should I pay your developer to do that for me? and I'm a student and I hope you notice this in the payment :)

**Comment by mufarex** [comment] 2022-02-23 16:20
?

**Comment by mufarex** [comment] 2022-02-26 13:12
Hello. I hope you are doing well. As i mentioned above I really need help on this issue becouse I have deadline for my project. I'll appreciate for your help. Please send me the cost. Thank you webmail.mufarex@gmail.com

**Comment by bitlogik** [comment] 2022-03-02 20:47
We sent a proposal by email replied on Feb 21st. We just forwarded it to this new email address.

**Closed by bitlogik** 2022-03-02 20:47 UTC
